computer:
  name: DESKTOP-BEELINK
  os: Windows 11 Pro

install_packages:
  - Git.Git
  - GitHub.cli
  - Microsoft.WindowsTerminal
  - Microsoft.PowerShell
  - Microsoft.VisualStudioCode
  - Microsoft.PowerToys
  - eza-community.eza

uninstall_packages:
  - Microsoft.MixedReality.Portal
  - Microsoft.Xbox.TCUI
