. "$PSScriptRoot\..\helpers.ps1"
# . "$PSScriptRoot\qBittorrent.ps1"
# . "$PSScriptRoot\MicaForEveryone.ps1"
# . "$PSScriptRoot\DiskO.ps1"
. "$PSScriptRoot\PowerToys.ps1"
# . "$PSScriptRoot/ccleaner.ps1"
